### ISSUE TITLE
Possible to implement IFTTT or/and SONOS API?

### ISSUE THREAD

**Issue by tomtechie** [dinofizz/diskplayer#1]
Hey,
Love the Idea. 
Super clean and fun way to play some music with style.

Would be interesting to implement this with for example IFTTT and/or SONOS.
Is this something you think would be possible?

**Comment by tomtechie** [comment]
Would love to support this project. U should add a "buy me a coffee"

**Comment by dinofizz** [comment]
>Hey,
>Love the Idea.
>Super clean and fun way to play some music with style.

Thanks for the kind words!

>Would be interesting to implement this with for example IFTTT and/or SONOS.
>Is this something you think would be possible?

I've not played with the IFTTT or SONOS API myself, but perhaps there are other examples online somewhere where people have integrated into these systems.

>Would love to support this project. U should add a "buy me a coffee"

Ah thank you I do appreciate that! At this moment I don't think I'll be making any further changes. It works for my needs, I'm quite excited to move on to the next project I have in mind... :) Feel free to fork it and develop it further yourself!

I myself was looking to buy a coffee for the dev(s) for these projects, but also didn't find any way to do so:

https://github.com/librespot-org/librespot
https://github.com/Spotifyd/spotifyd
https://github.com/zmb3/spotify

As without them, mine wouldn't be possible.
